#!/bin/bash

if [ "$1" != "" ]; then
  # Check if it is a GitHub issue URL
  pattern="^https://github.*/.*/issues/[0-9]+$"
  if [[ $1 =~ $pattern ]]; then
    issue=$1
  else
    echo "Invalid URL"
    exit 1
  fi
else
  echo "Usage: $0"
  echo "  $0 <GitHub Issue URL>"
  exit 1
fi

echo "---"
echo "gh issue view $issue"
echo "---"
gh issue view $issue

echo "---"
echo "gh issue view --comments $issue"
echo "---"
gh issue view --comments $issue
