#!/bin/bash

if [ "$1" != "" ]; then
  pattern="^https://github.*/.*pull/[0-9]+$"
  # Check if it is a GitHub pull request URL
  if [[ $1 =~ $pattern ]]; then
    pull=$1
  else
    echo "Invalid URL"
    exit 1
  fi
else
  echo "Usage: $0"
  echo "  $0 <GitHub PR URL>"
  exit 1
fi

echo "---"
echo "gh pr view $pull"
echo "---"
gh pr view $pull

echo "---"
echo "gh pr diff $pull"
echo "---"
# Measure the number of lines in the diff
diff_output=$(gh pr diff $pull)
diff_lines=$(echo "$diff_output" | wc -l)

# Check if the number of lines exceeds the threshold
threshold=1000  # Threshold for the allowable number of lines
if [ "$diff_lines" -gt "$threshold" ]; then
  echo "Diff is too large ($diff_lines lines). Ignoring..."
else
  echo \`\`\`diff
  echo "$diff_output"
  echo \`\`\`
fi

echo "---"
echo "gh pr view --comments $pull"
echo "---"
gh pr view --comments $pull
